export const emojiUrl = 'https://imgcache.qq.com/open/qcloud/tim/assets/emoji/'
export const emojiMap = {
  '[NO]': 'emoji_0@2x.png',
  '[OK]': 'emoji_1@2x.png',
  '[Rain]': 'emoji_2@2x.png',
  '[Moda da]': 'emoji_3@2x.png',
  '[Ping pong]': 'emoji_4@2x.png',
  '[Poo]': 'emoji_5@2x.png',
  '[Envelope]': 'emoji_6@2x.png',
  '[Snickering]': 'emoji_7@2x.png',
  '[Arrogance]': 'emoji_8@2x.png',
  '[Goodbye]': 'emoji_9@2x.png',
  '[Cold sweat]': 'emoji_10@2x.png',
  '[Withering]': 'emoji_11@2x.png',
  '[Knife]': 'emoji_12@2x.png',
  '[Delete]': 'emoji_13@2x.png',
  '[Seduce]': 'emoji_14@2x.png',
  '[In a daze]': 'emoji_15@2x.png',
  '[Shivering]': 'emoji_16@2x.png',
  '[Poor]': 'emoji_17@2x.png',
  '[Cute]': 'emoji_18@2x.png',
  '[Right hum]': 'emoji_19@2x.png',
  '[Right tai chi]': 'emoji_20@2x.png',
  '[Right front]': 'emoji_21@2x.png',
  '[Spit]': 'emoji_22@2x.png',
  '[Scare]': 'emoji_23@2x.png',
  '[Cursing]': 'emoji_24@2x.png',
  '[Coffee]': 'emoji_25@2x.png',
  '[Beer]': 'emoji_26@2x.png',
  '[Shh]': 'emoji_27@2x.png',
  '[Back]': 'emoji_28@2x.png',
  '[Sleepy]': 'emoji_29@2x.png',
  '[Bad laugh]': 'emoji_30@2x.png',
  '[Cloudy]': 'emoji_31@2x.png',
  '[Soldier]': 'emoji_32@2x.png',
  '[Crying]': 'emoji_33@2x.png',
  '[Sun]': 'emoji_34@2x.png',
  '[Struggle]': 'emoji_35@2x.png',
  '[Bottle]': 'emoji_36@2x.png',
  '[Grievance]': 'emoji_37@2x.png',
  '[Shy]': 'emoji_38@2x.png',
  '[Awkward]': 'emoji_39@2x.png',
  '[Left hum]': 'emoji_40@2x.png',
  '[Left tai chi]': 'emoji_41@2x.png',
  '[Left Front]': 'emoji_42@2x.png',
  '[Bad]': 'emoji_43@2x.png',
  '[Weak]': 'emoji_44@2x.png',
  '[Strong]': 'emoji_45@2x.png',
  '[Streamers]': 'emoji_46@2x.png',
  '[Color ball]': 'emoji_47@2x.png',
  '[Proud]': 'emoji_48@2x.png',
  '[Smile]': 'emoji_49@2x.png',
  '[Heartbreak]': 'emoji_50@2x.png',
  '[Crying]': 'emoji_51@2x.png',
  '[OU fire]': 'emoji_52@2x.png',
  '[Rage]': 'emoji_53@2x.png',
  '[Panic]': 'emoji_54@2x.png',
  '[Surprised]': 'emoji_55@2x.png',
  '[Silly laughs]': 'emoji_56@2x.png',
  '[Pistol]': 'emoji_57@2x.png',
  '[Yawning]': 'emoji_58@2x.png',
  '[Freaking out]': 'emoji_59@2x.png',
  '[Torture]': 'emoji_60@2x.png',
  '[Nose pulling]': 'emoji_61@2x.png',
  '[Hug]': 'emoji_62@2x.png',
  '[Boxing]': 'emoji_63@2x.png',
  '[Fist]': 'emoji_64@2x.png',
  '[Waving]': 'emoji_65@2x.png',
  '[Handshake]': 'emoji_66@2x.png',
  '[Skimming]': 'emoji_67@2x.png',
  '[Sweat]': 'emoji_68@2x.png',
  '[Banging]': 'emoji_69@2x.png',
  '[Halo]': 'emoji_70@2x.png',
  '[Moon]': 'emoji_71@2x.png',
  '[Lollipop]': 'emoji_72@2x.png',
  '[Car]': 'emoji_73@2x.png',
  '[Sofa]': 'emoji_74@2x.png',
  '[Sweating]': 'emoji_75@2x.png',
  '[Tears]': 'emoji_76@2x.png',
  '[Agitation]': 'emoji_77@2x.png',
  '[Light bulb]': 'emoji_78@2x.png',
  '[Bomb]': 'emoji_79@2x.png',
  '[Panda]': 'emoji_80@2x.png',
  '[Burst tendons]': 'emoji_81@2x.png',
  '[Love you]': 'emoji_82@2x.png',
  '[Love]': 'emoji_83@2x.png',
  '[Love]': 'emoji_84@2x.png',
  '[Pigs head]': 'emoji_85@2x.png',
  '[Cat]': 'emoji_86@2x.png',
  '[Kiss]': 'emoji_87@2x.png',
  '[Rose]': 'emoji_88@2x.png',
  '[Ladybug]': 'emoji_89@2x.png',
  '[Question]': 'emoji_90@2x.png',
  '[White eyes]': 'emoji_91@2x.png',
  '[Ball]': 'emoji_92@2x.png',
  '[Sleeping]': 'emoji_93@2x.png',
  '[Kowtow]': 'emoji_94@2x.png',
  '[Show love]': 'emoji_95@2x.png',
  '[Gift bag]': 'emoji_96@2x.png',
  '[Gift]': 'emoji_97@2x.png',
  '[Basketball]': 'emoji_98@2x.png',
  '[Rice]': 'emoji_99@2x.png',
  '[Embarrassing]': 'emoji_100@2x.png',
  '[Red Double Happiness]': 'emoji_101@2x.png',
  '[Red Lantern]': 'emoji_102@2x.png',
  '[Tissue]': 'emoji_103@2x.png',
  '[Victory]': 'emoji_104@2x.png',
  '[Color]': 'emoji_105@2x.png',
  '[Medicine]': 'emoji_106@2x.png',
  '[Kitchen knife]': 'emoji_107@2x.png',
  '[Cake]': 'emoji_108@2x.png',
  '[Candle]': 'emoji_109@2x.png',
  '[Hip-hop]': 'emoji_110@2x.png',
  '[Bad]': 'emoji_111@2x.png',
  '[Watermelon]': 'emoji_112@2x.png',
  '[Naughty]': 'emoji_113@2x.png',
  '[Chess]': 'emoji_114@2x.png',
  '[Skipping rope]': 'emoji_115@2x.png',
  '[Jump jump]': 'emoji_116@2x.png',
  '[Carriage]': 'emoji_117@2x.png',
  '[Circle]': 'emoji_118@2x.png',
  '[Despise]': 'emoji_119@2x.png',
  '[Cool]': 'emoji_120@2x.png',
  '[Banknote]': 'emoji_121@2x.png',
  '[Diamond ring]': 'emoji_122@2x.png',
  '[Lightning]': 'emoji_123@2x.png',
  '[Shut up]': 'emoji_124@2x.png',
  '[Alarm clock]': 'emoji_125@2x.png',
  '[Insidious]': 'emoji_126@2x.png',
  '[Sad]': 'emoji_127@2x.png',
  '[Umbrella]': 'emoji_128@2x.png',
  '[Frog]': 'emoji_129@2x.png',
  '[Noodles]': 'emoji_130@2x.png',
  '[Firecrackers]': 'emoji_131@2x.png',
  '[Windmill]': 'emoji_132@2x.png',
  '[Kiss]': 'emoji_133@2x.png',
  '[Airplane]': 'emoji_134@2x.png',
  '[Hunger]': 'emoji_135@2x.png',
  '[Banana]': 'emoji_136@2x.png',
  '[Skull]': 'emoji_137@2x.png',
  '[Microphone]': 'emoji_138@2x.png',
  '[Mahjong]': 'emoji_139@2x.png',
  '[Applause]': 'emoji_140@2x.png',
  '[Grin]': 'emoji_141@2x.png'
}
export const emojiName = [
  '[Grinning teeth]',
  '[Naughty]',
  '[Sweating]',
  '[Chuckles]',
  '[Goodbye]',
  '[Banging]',
  '[Sweats]',
  '[Pigs head]',
  '[Rose]',
  '[Tears]',
  '[Crying]',
  '[Shh]',
  '[Cool]',
  '[Freaking out]',
  '[Grievance]',
  '[Poop]',
  '[Bomb]',
  '[Kitchen knife]',
  '[Cute]',
  '[Color]',
  '[Shy]',
  '[Proud]',
  '[Spits]',
  '[Smiles]',
  '[Anger]',
  '[Awkward]',
  '[In horror]',
  '[Cold sweat]',
  '[Love]',
  '[Show love]',
  '[White eyes]',
  '[Arrogance]',
  '[Sad]',
  '[Surprised]',
  '[Doubt]',
  '[Sleepy]',
  '[Mo-Mo-da]',
  '[Chuckles]',
  '[Love]',
  '[Fades]',
  '[Skimming]',
  '[Insidious]',
  '[Struggle]',
  '[In a daze]',
  '[Right humming]',
  '[Hugs]',
  '[Chuckles]',
  '[Kisses]',
  '[Despises]',
  '[Halo]',
  '[Soldier]',
  '[Pitiful]',
  '[Strong]',
  '[Weak]',
  '[Shaking hands]',
  '[Victory]',
  '[Boxing]',
  '[Fades]',
  '[Rice]',
  '[Cake]',
  '[Watermelon]',
  '[Beer]',
  '[Ladybug]',
  '[Seducing]',
  '[OK]',
  '[Love you]',
  '[Coffee]',
  '[Moon]',
  '[Knife]',
  '[Shivering]',
  '[Lousy]',
  '[Fists]',
  '[Heartbreak]',
  '[Sun]',
  '[Gift]',
  '[Ball]',
  '[Skull]',
  '[Waving]',
  '[Lightning]',
  '[Hunger]',
  '[Cursing]',
  '[Torture]',
  '[Nose pulling]',
  '[Clapping]',
  '[Embarrassing]',
  '[Left grunting]',
  '[Yawning]',
  '[Crying]',
  '[Frightens]',
  '[Basketball]',
  '[Ping-pong]',
  '[NO]',
  '[Jumping]',
  '[OU fire]',
  '[Circling]',
  '[Kowtowing]',
  '[Turning back]',
  '[Skipping rope]',
  '[Agitation]',
  '[Hip-hop]',
  '[Kiss]',
  '[Left tai chi]',
  '[Right tai chi]',
  '[Shut up]',
  '[Cat]',
  '[Red Double Happiness]',
  '[Firecrackers]',
  '[Red Lantern]',
  '[Mahjong]',
  '[Microphone]',
  '[Gift bag]',
  '[Envelope]',
  '[Chess]',
  '[Streamers]',
  '[Candle]',
  '[Exploding tendons]',
  '[Lollipop]',
  '[Bottle]',
  '[Noodles]',
  '[Banana]',
  '[Airplane]',
  '[Left Front]',
  '[Carriage]',
  '[Right front]',
  '[Cloudy]',
  '[It rains]',
  '[Money]',
  '[Panda]',
  '[Light bulb]',
  '[Windmill]',
  '[Alarm clock]',
  '[Umbrella]',
  '[Colored ball]',
  '[Diamond ring]',
  '[Sofa]',
  '[Tissue]',
  '[Pistol]',
  '[Frog]'
]
